# redis-server.yml
version: '3.7'
services:
  django:
    build: .
    command: "sh command.sh ${PORT}"
    container_name: boiler
    hostname: root
    volumes:
      - .:/usr/src/app
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped